servos:
  leg_l_hip: { id: 0, pin: 9, range: [20, 160], start: 19 }
  leg_l_knee: { id: 1, pin: 10, range: [5, 175], start: 12 }
  leg_l_ankle: { id: 2, pin: 11, range: [40, 180], start: 52 }
  leg_r_hip: { id: 3, pin: 6, range: [20, 160], start: 93 }
  leg_r_knee: { id: 4, pin: 7, range: [5, 175], start: 190 }
  leg_r_ankle: { id: 5, pin: 8, range: [40, 180], start: 88 }
  tilt: { id: 6, pin: 2, range: [60, 120], start: 75 }
  pan: { id: 7, pin: 3, range: [20, 160], start: 50 }
