vision:
  tech: "coral"
  initial_mode: "object"
  modes: ["object", "face"]
  debug: false
  docs:
    description: "The vision module is used to detect objects and faces."
    events: 
      sub: 
        - exit:
            description: "Exit module."
      pub: 
        - log:
            description: "Send messages to logger."
        - vision:detect:object:
            description: "The vision module has detected an object."
            args:
              - name: string
        - vision:detect:face:
            description: "The vision module has detected a face."
              - name: string
        - vision:matches:
            description: "List of vision matches."
              - matches: array
              - labels: array
        - vision:nomatch:
            description: "No matches."
